In [14]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pylab as plt
import folium

In [2]:
df = pd.read_csv("C:/Users/Mainaki Saraf/Desktop/Sem 5/DA/Project/Dataset/Sample_data_2017.csv")

In [7]:
df.columns

Index(['Unnamed: 0', 'Summons Number', 'Plate ID', 'Registration State',
       'Plate Type', 'Issue Date', 'Violation Code', 'Vehicle Body Type',
       'Vehicle Make', 'Issuing Agency', 'Street Code1', 'Street Code2',
       'Street Code3', 'Vehicle Expiration Date', 'Violation Location',
       'Violation Precinct', 'Issuer Precinct', 'Issuer Code',
       'Issuer Command', 'Issuer Squad', 'Violation Time',
       'Time First Observed', 'Violation County',
       'Violation In Front Of Or Opposite', 'House Number', 'Street Name',
       'Intersecting Street', 'Date First Observed', 'Law Section',
       'Sub Division', 'Violation Legal Code', 'Days Parking In Effect    ',
       'From Hours In Effect', 'To Hours In Effect', 'Vehicle Color',
       'Unregistered Vehicle?', 'Vehicle Year', 'Meter Number',
       'Feet From Curb', 'Violation Post Code', 'Violation Description',
       'No Standing or Stopping Violation', 'Hydrant Violation',
       'Double Parking Violation'],
      dtype='object')

In [20]:
df.iloc[:,25:30]

,Street Name,Intersecting Street,Date First Observed,Law Section,Sub Division
0,REGIS DRIVE,NaN,0,408,F1
1,Broadway,NaN,0,408,c3
2,E 187TH ST,NaN,0,408,D1
3,SB BAILEY AVE @ W 22,5TH ST,0,1180,B
4,E 17th St,NaN,0,408,d1
5,WB 31 AV 76 ST - 68,ST,0,1180,B
6,EB EASTERN PKWY @ WA,SHINGTON AVE,0,1180,B
7,W 45th St,15ft W/of 5th Ave,0,408,c
8,Broadway,NaN,0,408,c
9,VAN WYCK EXP SVC RD,(N/B) @ ROCKAWAY BLV,0,1111,D
10,Dobbin St,NaN,0,408,d
11,WB FLATLANDS AVE @ E,SSEX ST,0,1180,B
12,E 47th St,3rd Ave,0,408,e1
13,42nd Ave,NaN,0,408,h1
14,Sterling Pl,NaN,0,408,h1
15,22nd St,NaN,0,408,j6
16,WB E HOUSTON ST. FDR,DR - AVE C,0,1180,B
17,Queens Blvd,NaN,0,408,c3
18,Wallabout St,10ft E/of Franklin A,0,408,c
19,SB WEBSTER AVE @ E 1,94TH ST,0,1111,C
20,E 29 ST,NaN,0,408,D1
21,Greenwich St,NaN,0,408,c
22,E 22nd St,30ft E/of Broadway,0,408,h1
23,E 161 ST,NaN,0,408,K6
24,30th Ave,NaN,0,408,h1
25,SB SPRINGFIELD BLVD,@ HOLLIS AVE,0,1180,B
26,PENNSYLVANIA AVE (N/,B) @ LINDEN BLVD,0,1111,D
27,NB MAIN ST @ REEVES,AVE,0,1180,B
28,Shore Rd,NaN,0,408,j2
29,SB RALPH AVE @ BEVER,LEY RD,0,1180,B
...,...,...,...,...,...
1080273,Austin St,NaN,0,408,h1
1080274,7th Ave,NaN,0,408,l4
1080275,WB EASTERN PKWY @ CL,ASSON AVE,0,1180,B
1080276,Cedar St,10ft W/of Nassau St,0,408,h1
1080277,King St,8ft E/of Varick St,0,408,h1
1080278,Charlton St,NaN,0,408,c4
1080279,HORACE HARDING EXPWY,(E/B) @ 173RD ST,0,1111,D
1080280,SB WEBSTER AVE @ E 1,94TH ST,0,1111,C
1080281,QUEENS BLVD (E/B) @,39TH ST,0,1111,D
1080282,Skillman Ave,NaN,0,408,d
1080283,Vanderbilt Ave,NaN,0,408,h1
1080284,BEACH CHANNEL DR (W/,B) @ B 140TH ST,0,1111,D
1080285,3rd Ave,NaN,0,408,d
1080286,21st Ave,NaN,0,408,j5
1080287,67th St,NaN,0,408,d1
1080288,10th St,NaN,0,408,d1
1080289,214th Pl,NaN,0,408,j3
1080290,13th Ave,NaN,0,408,h1
1080291,Forest Ave,15ft N/of Stephen St,0,408,h1
1080292,PINE ST,NaN,0,408,E2
1080293,Havemeyer St,NaN,0,408,h1
1080294,32nd St,NaN,0,408,d
1080295,Stanton St,NaN,0,408,F1
1080296,QUEENS MIDTOWN EXPWY,(W/B) @ 43RD ST,0,1111,D
1080297,E 23rd St,NaN,0,408,p
1080298,56th Ave,NaN,0,408,k4
1080299,E 46th St,15ft E/of 5th Ave,0,408,l3
1080300,101st Ave,NaN,0,408,d1
1080301,W 84th St,NaN,0,408,c4
1080302,EB UNION TPK. 255 ST,- 262 ST,0,1180,B

In [15]:
#plot basic map of New York
def generateBaseMap(default_location=[40.693943, -73.985880], default_zoom_start=12):
    base_map = folium.Map(location=default_location, control_scale=True, zoom_start=default_zoom_start)
    return base_map

In [16]:
base_map = generateBaseMap()
base_map